[project]
name = "generatepdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chardet>=5.2.0",
    "numpy>=2.3.4",
    "pillow>=12.0.0",
    "pypdf2>=3.0.1",
    "reportlab>=4.4.4",
]
